# Generated by Django 6.1 on 2026-08-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='stock_after',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_before',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
