# Generated by Django 6.1 on 2026-08-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stockmovement_stock_after_stockmovement_stock_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='stock_before',
            new_name='stock_initial',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
